apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'ls -l /dev/|tee /mnt/test/a;sleep 1000']
      volumeMounts:
        - name: mypvc
          mountPath: /mnt/test
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: busybox-pvc
        readOnly: false
