apiVersion: apps/v1
kind: Deployment
metadata:
  name: d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asdf
  template:
    metadata:
      labels:
        app: asdf
    spec:
      containers:
      - image: busybox
        name: p
        imagePullPolicy: IfNotPresent
        command:
          - 'sh'
        args:
          - -c
          - echo $(date) "Hello, Kubernetes!"; sleep 1000
