apiVersion: v1
kind: Pod
metadata:
  name: p
spec:
  containers:
    - name: c
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'dd if=/dev/rand of=/dev/block bs=512 count=1; sleep 1000']
      volumeDevices:
        - name: mypvc
          devicePath: /dev/block
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: p-pvc
        readOnly: false
